- .github/workflows/build.sh
- .github/workflows/configure.sh
- .github/workflows/main.yml
- .github/workflows/setup_env.sh
- .github/workflows/test.sh
- include/blas/rotg.hh
Fix minor differences so a multi-way diff
```
meld testsweeper/.github/workflows blaspp/.github/workflows lapackpp/.github/workflows
```
shows only significant changes, e.g., blaspp has devices.
> Synchronize CI workflow across projects

- config/rocblas.cc
- include/blas/device.hh
Resolves deprecated warnings. Cf. https://bitbucket.org/icl/blaspp/issues/20/rocm-520-deprecated-header
> update include path for ROCm 5.2; fixes bitbucket issue #20

- include/blas/device.hh
- src/device_utils.cc
- test/test_memcpy.cc
- test/test_memcpy_2d.cc
* Rename device_malloc_pinned to host_malloc_pinned, since it is host memory.
* Deprecate old routines in Doxygen. We will do C++ deprecation once SLATE is updated.
* Update docs and clean code a bit.
This PR comes after the `memcpy` PR.
> Host malloc

- test/test.cc
- test/test_asum.cc
- test/test_axpy.cc
- test/test_axpy_device.cc
- test/test_copy.cc
- test/test_copy_device.cc
- test/test_dot.cc
- test/test_dotu.cc
- test/test_gemv.cc
- test/test_ger.cc
- test/test_geru.cc
- test/test_hemv.cc
- test/test_her.cc
- test/test_her2.cc
- test/test_iamax.cc
- test/test_nrm2.cc
- test/test_nrm2_device.cc
- test/test_rot.cc
- test/test_rotg.cc
- test/test_rotm.cc
- test/test_rotmg.cc
- test/test_scal.cc
- test/test_scal_device.cc
- test/test_swap.cc
- test/test_swap_device.cc
- test/test_symv.cc
- test/test_syr.cc
- test/test_syr2.cc
- test/test_trmv.cc
- test/test_trsv.cc
TestSweeper allows headers to be 2 lines, which is nice for compact output, but harder to parse, e.g., by pandas. Use 1 line headers for ease of parsing. Also match SLATE's header names. Note it's fine to have space in a header. Columns are separated by 2 spaces, which is how we split data for pandas.
> test: change 2-line headers to 1-line headers and adjust widths

- .github/workflows/build.sh
- .github/workflows/configure.sh
- .github/workflows/setup_env.sh
- .github/workflows/test.sh
- CMakeLists.txt
- INSTALL.md
- blasppConfig.cmake.in
- cmake/BLASFinder.cmake
- cmake/util.cmake
- test/CMakeLists.txt
- Use newer find_package( CUDAToolkit ).
- If using CUDA, export find_dependency. Addresses https://bitbucket.org/icl/blaspp/issues/23. The example smoke tests compile fine before and after, so I can't actually replicate a problem.
- Tweak CMake output.
- CMake finds CUDA in /usr/local/cuda even if it isn't "loaded", so needed to update the CI build scripts to set gpu_target explicitly. Added a check that the CPU-only version does not link with cublas or rocblas, which required changing how errors are handled in the CI build scripts.
> Cmake CUDA update

- CMakeLists.txt
- cmake/LAPACKFinder.cmake
- include/blas/wrappers.hh
- test/CMakeLists.txt
BLAS++ wraps `rot`. Unfortunately, technically some variants are in BLAS (srot, drot, csrot, zdrot), while some are in LAPACK (crot, zrot).
```
lapack> pfind 'rot.f$'
./BLAS/SRC/csrot.f
./BLAS/SRC/drot.f
./BLAS/SRC/srot.f
./BLAS/SRC/zdrot.f
./SRC/crot.f
./SRC/zrot.f
```
This isn't a problem for libraries that include both BLAS and LAPACK, like OpenBLAS, Intel MKL, Cray LibSci. But it can be an issue for libraries like BLIS that don't include LAPACK. (IBM ESSL includes `[cz]rot`, though it doesn't include all of LAPACK.)
The solution here is to find and link with the LAPACK library. The configure.py / Makefile build already does this.
A similar issue affects `[cz]symv` and `[cz]syr`. The previous solution for those was to put them in LAPACK++, but still in the blas namespace, which is …
> Cmake link with lapack

- INSTALL.md
- cmake/BLASConfig.cmake
- cmake/BLASFinder.cmake
- cmake/CBLASConfig.cmake
- cmake/LAPACKFinder.cmake
When cross-compiling, BLAS++ needs some extra information because it can't effectively probe the system. It can detect link-time differences (gemm_ vs. gemm vs. GEMM) but not run-time differences (int32 vs. int64, how complex is returned). [Per CMake's docs](https://cmake.org/cmake/help/latest/command/try_run.html?highlight=try_run#behavior-when-cross-compiling), when cross-compiling, `try_run` compiles but doesn't run the code. This PR sets `run_output` and `run_result` to values _as if_ it had run, with certain assumptions. The user must supply several items that cannot be probed (see INSTALL.md):
- `blas_int`
- `blas_complex_return`
- [optional] `blas_return_float_f2c`. This will be set automatically for macOS Accelerate, the only currently affected BLAS library in common use.
This PR …
> Cmake cross-compiling

- include/blas/device_blas.hh
- include/blas/wrappers.hh
- src/batch_gemm.cc
- src/batch_hemm.cc
- src/batch_her2k.cc
- src/batch_herk.cc
- src/batch_symm.cc
- src/batch_syr2k.cc
- src/batch_syrk.cc
- src/batch_trmm.cc
- src/batch_trsm.cc
Refactors batch routines, same way as PR #18.
Also reformats the headers to alphabetize routines and minimize diff when doing:
```
meld include/blas/wrappers.hh include/blas/device_blas.hh
```
This builds on PR #21.
> Refactor batch

- CMakeLists.txt
- src/device_batch_gemm_group.cc
- src/device_batch_hemm.cc
- src/device_batch_her2k.cc
- src/device_batch_herk.cc
- src/device_batch_symm.cc
- src/device_batch_syr2k.cc
- src/device_batch_syrk.cc
- src/device_batch_trmm.cc
- src/device_batch_trsm.cc
Refactors GPU device batch routines, same way as PR https://github.com/icl-utk-edu/blaspp/pull/22.
This builds on PR https://github.com/icl-utk-edu/blaspp/pull/22.
For reviewing code, I recommend comparing against the CPU implementation (from PR #22):
```
git fetch -f https://github.com/mgates3/blaspp.git refactor-dev-batch:refactor-dev-batch
git checkout refactor-dev-batch
mkdir tmp2
cp src/batch*.cc tmp2/
cd tmp2
for x in *.cc ; do mv $x device_$x ; done
perl -pi -e 's/CPU,/GPU device,/' *.cc
cd ..
meld tmp2 src
```
Fixed-size batched gemm and trsm call GPU-native routines. Other routines and variable-size batch gemm and trsm use a multi-stream implementation, basically replacing `#pragma omp parallel for` with `queue.fork() ... queue.revolve(); ... queue.join();`.
> Refactor GPU device batch

- example/example_gemm.cc
- example/example_util.cc
- example/util.hh
Some GPUs don't support double precision, so we need control over which precisions are run in smoke tests. This adds command line options to select precisions. To run only single and single-complex:
```
./example_gemm s c
./example_util s c
```
> add data type options to examples for smoke test

- .github/workflows/test.sh
Previously, I thought CMAKE_PREFIX_PATH had to point to the specific package's directory:
```
${top}/install/lib/blaspp
```
but found that pointing to the install directory is sufficient:
```
${top}/install
```
which greatly simplifies scripts when there are multiple packages to point to.
> ci: simplify CMAKE_PREFIX_PATH

- include/blas/device.hh
- src/blas_internal.hh
- src/device_dot.cc
- src/device_internal.hh
- src/device_nrm2.cc
- test/test.cc
For SYCL the dev-dot, dev-dotu, dev-nrm2 need to be updated (need to check the result pointer, and if it was cpu-malloc'ed, then create a temporary result_dev to hold the result).  
```
./tester  --type s,d,c,z --dim 100 --incx 1,-1 --incy 1,-1 --pointer-mode h,d dev-dot
./tester  --type s,d,c,z --dim 100 --incx 1,-1 --incy 1,-1 --pointer-mode h,d dev-dotu
./tester  --type s,d,c,z --dim 100 --incx 1 --pointer-mode h,d dev-nrm2
```
These tests used to fail with `--pointer-mode h`  but all pass now.
> For SYCL/OneMKL, update dev-dot, dev-dotu, dev-nrm2 to allow cpu-malloc result pointers.

- test/run_tests.py
Helpful to restart an interrupted run, or after fixing an issue with a routine. Example use:
```
frontier08753 blaspp/test> ./run_tests.py --device > device.txt
Wed Mar  8 11:23:37 2023
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2,-1,-2 --incy 1,2,-1,-2 dev-axpy
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2,-1,-2 --incy 1,2,-1,-2 dev-dot
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2,-1,-2 --incy 1,2,-1,-2 dev-dotu
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2 dev-nrm2
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2 dev-scal
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2,-1,-2 --incy 1,2,-1,-2 dev-swap
pass
./tester  --type s,d,c,z --dim 100:500:100 --incx 1,2,-1,-2 --incy 1,2,-1,-2 dev-copy
pass
./tester  --type …
```
> test: add --start option

- test/test.cc
- test/test_schur_gemm.cc
Add transA, transB option to Schur gemm test.
Add multi-stream gemm for comparison. This chops into tiles and executes a gemm for each tile in separate streams, using Queue's fork mechanism.
> Schur gemm test

- .github/workflows/setup_env.sh
- INSTALL.md
- config/config.py
Instead of requiring the user to add CUDA and ROCm to CFLAGS, LIBRARY_PATH, LD_LIBRARY_PATH, this does a quick search for them and adds the appropriate `-I`, `-L`, and `-rpath` flags. (CMake already does this.)
Similar changes are in SLATE and LAPACK++. The BLAS++ changes will need to be merged first, then LAPACK++, then SLATE submodules updated.
> search for ROCm or CUDA

- CMakeLists.txt
Checks if the compiler supports the -fsycl flag.  
Use oneMKL-SYCL-device if oneMKL is available and  the fsycl compiler flag works.
Otherwise, just use the standard MKL.
This allows building with the GNU compiler and using oneMKL BLAS (without SYCL-devices).
On leconte, using the following with GNU works, but does not find oneMKL+SYCL devices, so it configures with just cpu-MKL.
cmake -Dgpu_backend=onemkl ..
> To Cmake, added sycl-compiler check before setting up oneMKL-SYCL-device

- .github/workflows/test.sh
- config/blas.cc
- config/cblas.cc
- config/lapack.py
- config/return_complex.cc
- config/return_complex_argument.cc
- config/return_float.cc
- config/return_float_f2c.cc
- example/example_gemm.cc
3 minor updates:
- Update `example_gemm.cc` to match Queue revisions. It was printing "deprecated" warnings. Also flag such warnings as errors in CI.
- Use `_Complex` as return type for `zdotc` in config. clang++ was raising errors with extern C linkage. Also add some output to help debugging when users report issues.
- Remove some obsolete settings from 2020.
I highlighted these 3 things in GitHub conversations in the code.
> Fix smoke test example and config

- .github/workflows/configure.sh
- cmake/LAPACKFinder.cmake
- config/config.h
- include/blas/batch_common.hh
- include/blas/config.h
- test/cblas_wrappers.cc
- test/test.hh
Fixes blas_int(value) cast when blas_int is long long. Originally:
```
src/blas_internal.hh: In function 'long long int blas::to_blas_int_(int64_t, const char*)':
./include/blas/config.h:13:39: error: expected primary-expression before 'long'
13 |         #define blas_int              long long  /* or int64_t */
```
The cblas wrappers also had an error respecting int64:
```
test/cblas_wrappers.cc: In function 'void cblas_rot(int, std::complex<float>*, int, std::complex<float>*, int, float, std::complex<float>)':
test/cblas_wrappers.cc:52:9: error: cannot convert 'int*' to 'const blas_int*' {aka 'const long int*'}
52 |         &n,
```
Regarding `#define` use, see https://stackoverflow.com/a/638759/1655607
> Use typedef instead of #define. Use int64_t to be unambiguous.

- CMakeLists.txt
The CMake configuration files normally go into `${CMAKE_INSTALL_LIBDIR}/cmake/<lib-name>`, which conforms the CMake practice.
Ref: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8111
> Change installation directory of CMake config files

- CMakeLists.txt
- cmake/LAPACKFinder.cmake
Avoids conflict with LAPACK++ so it can find `-llapack` with ESSL.
The issue is BLAS++ needs a subset of LAPACK, which is provided by ESSL (e.g., potrf), whereas LAPACK++ needs the whole of LAPACK (e.g., pstrf, lacpy, laset, ...), which is provided by Netlib LAPACK in `-llapack`. The BLAS++ CMake runs first and discovers ESSL, then LAPACK++ CMake runs and saw the cached value. This PR makes a namespace to avoid LAPACK++ seeing the cached value from BLAS++.
> cmake: add blaspp_ namespace

- src/syr2.cc
Fix ODR violations in `syr2k` / `syr2` by delegating complex `syr2` to the top-level `blas::syr2k`. Fixes https://github.com/icl-utk-edu/blaspp/issues/65
> Fix CMAKE_UNITY_BUILD

- include/blas/device.hh
`lwork_` is sometimes set larger than the actual allocation.  Then, when `work_ensure_size` is called again with a slightly larger request, it looks like the workspace is big enough when it's actually not.
> Fix mistake in Queue workspace allocation

- examples/example_gemm.cc
Didn't previously show because of hard-coded values `n = 200 > k = 50`. Using `n = 50 < k = 200`, it throws an error:
```
blaspp/examples> ./example_gemm
m 100, n 50, k 200
void test_gemm(int, int, int) [with T = float]
ldb < k, in function gemm
```
After this fix, it works:
```
blaspp/examples> ./example_gemm
m 100, n 50, k 200
void test_gemm(int, int, int) [with T = float]
void test_gemm(int, int, int) [with T = double]
void test_gemm(int, int, int) [with T = std::complex<float>]
void test_gemm(int, int, int) [with T = std::complex<double>]
void test_device_gemm(int, int, int) [with T = float]
no GPU devices
void test_device_gemm(int, int, int) [with T = double]
no GPU devices
void test_device_gemm(int, int, int) [with T = std::complex<float>]
no GPU devices
void test_device_gemm(int, …
```
> example: fix ldb=k in example_gemm. Resolves #75.

- src/rocblas_wrappers.cc
- test/test.cc
rocBLAS 3.0 in ROCm 5.6.0 introduced a 3 matrix trmm, with separate B and C matrices that can be aliased. See
https://rocblas.readthedocs.io/en/master/API_Reference_Guide.html#rocblas-xtrmm-batched-strided-batched
This updates BLAS++ to call the new interface when available.
Also print the CPU and GPU BLAS version, where known. Tested on various systems:
```
pangolin blaspp> ./test/tester
BLAS++ version 2023.11.05, id 92ad3b4f,  OpenBLAS 0.3.21 
pangolin blaspp> ./test/tester
BLAS++ version 2023.11.05, id 92ad3b4f, Apple Accelerate
methane blaspp> ./test/tester 
BLAS++ version 2023.11.05, id 92ad3b4f, Intel MKL 2023.0.2, CUDA 11.0.0
dopamine blaspp> ./test/tester
BLAS++ version 2023.11.05, id 92ad3b4f, Intel MKL 2023.0.2, ROCm 5.7.1
```
> rocm: support rocBLAS 3.0 trmm with 3 matrices A, B, C

- GNUmakefile
- include/blas/device.hh
- src/device_utils.cc
See description in https://github.com/icl-utk-edu/testsweeper/pull/23 and https://github.com/icl-utk-edu/testsweeper/pull/25.
Remove deprecated functions (before initial soversion). Deprecate MemcpyKind and related functions.
>  Add soversion to shared library

- src/rot.cc
- src/rotm.cc
Updates rot, rotm. Other routines already used `to_blas_int`. Check files:
```
blaspp/src> git re -l '\bblas_int\b' | xargs grep -L to_blas_int
blaspp/src> git re -l '\bdevice_blas_int\b' | xargs grep -L to_device_blas_int
cublas_wrappers.cc
device_utils.cc
onemkl_wrappers.cc
rocblas_wrappers.cc
blaspp/src> git re numeric_limits
blas_internal.hh:        blas_error_if_msg( x > std::numeric_limits<blas_int>::max(), "%s", x_str );
device_internal.hh:        blas_error_if_msg( std::abs( x ) > std::numeric_limits<device_blas_int>::max(),
```
> use to_blas_int to check overflow and convert int64_t

- CMakeLists.txt
- cmake/BLASFinder.cmake
- cmake/LAPACKFinder.cmake
- configure.py
- include/blas/fortran.h
- src/symv.cc
- src/syr.cc
- test/cblas_wrappers.cc
- test/cblas_wrappers.hh
- test/run_tests.py
- test/test_symv.cc
- test/test_syr.cc
- test/test_util.cc
This moves `[cz]symv` and `[cz]syr` into BLAS++, where they logically should reside, rather than LAPACK++, where they have resided for historical reasons. `[cz]symv` and `[cz]syr` are in LAPACK rather than Reference BLAS. Most vendors ship BLAS and LAPACK together (OpenBLAS, Intel MKL, Cray LibSci), so users don't notice the difference.
However, IBM ESSL notably has only a limited subset of LAPACK, and lacks `[cz]symv` and `[cz]syr`. For ESSL, users can also link with reference LAPACK to complete it. See https://www.ibm.com/docs/en/essl/6.3?topic=reference-lapack-lapacke.
This supersedes PR #86.
> Move [cz]symv and [cz]syr from LAPACK++

- CMakeLists.txt
- cmake/config.cmake
- config/config.py
- config/std_atomic.cc
- configure.py
> config: check for libatomic. Fixes #90.

- config/rocblas.cc
- include/blas/device.hh
Use of HIP_PLATFORM_HCC is deprecated and breaking the build when using rocm 6.3.2.  Switching to use HIP_PLATFORM_AMD.
> Converting HIP_PLATFORM_HCC to HIP_PLATFORM_AMD

- INSTALL.md
- cmake/BLASFinder.cmake
- cmake/util.cmake
- config/lapack.py
CMake updates:
* Use match() that sets boolean. The [CMake call](https://cmake.org/cmake/help/latest/command/string.html#regex-match) `string( REGEX MATCH regex output str )` stores the _actual_ matched string, not a boolean value. The actual matched string may be something that CMake considers false (no, false, 0, off, notfound, etc.), confounding the program logic.
* Add blas_threaded=openmp_aware, to allow linking with multi-threaded MKL in SLATE. Previously, SLATE by default restricts BLAS to sequential, since we want sequential BLAS in the OpenMP tasks. MKL is smart enough not to spawn new threads inside OpenMP tasks. [See MKL_DYNAMIC](https://www.intel.com/content/www/us/en/docs/onemkl/developer-guide-linux/2023-0/mkl-dynamic.html).
> CMake match

- .github/workflows/configure.sh
- .github/workflows/main.yml
- .github/workflows/variants.yml
The `variants.yml` didn't specify new tests correctly, per GitHub Action's (confusing) [matrix docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow). This fixes the variants, and tweaks the regular PR CT `main.yml` to test one `BLA_VENDOR`.
> ct: fix variants

- include/blas/util.hh
Fixes include error when compiling on Windows.
> fix stdint.h

- CMakeLists.txt
- include/blas/device_blas.hh
- src/cublas_wrappers.cc
- src/device_hemv.cc
- src/device_internal.hh
- src/device_symv.cc
- src/onemkl_wrappers.cc
- src/rocblas_wrappers.cc
- test/CMakeLists.txt
- test/run_tests.py
- test/test.cc
- test/test.hh
- test/test_hemv_device.cc
- test/test_symv_device.cc
Added cuBLAS, rocBLAS, and oneMKL wrappers for symv and hemv. Based on #116.
> Add device hemv, symv

- CMakeLists.txt
- include/blas/device_blas.hh
- src/cublas_wrappers.cc
- src/device_internal.hh
- src/device_trmv.cc
- src/device_trsv.cc
- src/onemkl_wrappers.cc
- src/rocblas_wrappers.cc
- test/CMakeLists.txt
- test/run_tests.py
- test/test.cc
- test/test.hh
- test/test_trmv_device.cc
- test/test_trsv_device.cc
Added cuBLAS, rocBLAS, and oneMKL wrappers for trmv and trsv. Based on #117.
> Add device trmv, trsv
